---
- name: Install Apache and upload my web Page
  hosts: web
  become: yes

  vars:
    source_file: ./MyWebSite/index.html
    destination_file: /var/www/html

  tasks:
  - name: Install Apache Web Server
    yum: name=httpd state=latest

  - name: Copy MyWebPage to server
    copy: src={{ source_file }} dest={{ destination_file }} mode=0555
    notify: Restart Apache

  - name: Start WebServer end enable on boot
    service: name=httpd state=started enabled=yes

  handlers:
  - name: Restart Apache
    service: name=httpd state=restarted
