---
- hosts: jenkins
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Enable EPEL Repository
    yum:
      name: epel-release
      state: present

  - name: yum update
    yum:
      name: '*'
      state: latest
  
  - name: Install java
    yum:
      name: java-1.8.0-openjdk-devel
      state: present

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started

  - name: Get Administrator Password
    command: cat initialAdminPassword chdir="/var/lib/jenkins/secrets/"
    register: command_output

  - name: Print Administrator Password
    debug: 
      msg: "Administrator password: {{command_output.stdout}} "